### ISSUE TITLE
Assignment 1 not merged into master

### ISSUE THREAD

**Issue by jeremyeng** [egan-seamus/software-dev#5]
Hi!

My partner and I are also in Software Dev. We received your repository for the Array API we're supposed to implement but we noticed that your `develop` branch hasn't yet been merged into master. I talked to Jan and he said that they automatically pull the tests from the master branch when they grade A2. Would you be able to merge that branch into master so we can complete the assignment?

-Jeremy

**Comment by egan-seamus** [comment]
Jeremy,
Good catch. I’ll get on that as soon as I can. If I haven’t by tonight, send me another email to remind me.
Seamus

**Comment by jeremyeng** [comment]
Hi Seamus,

Thanks for responding! We'd really appreciate if you could merge the branch into master sometime this evening.

-Jeremy and Nate

**Comment by jeremyeng** [comment]
Thanks again for placing your part2 code in master! Much appreciated.
